baseURL: "scripps.cairn.com"
languageCode: "en-us"
title: "Scripps College Projects"
pygmentsstyle: 'minted'
metaDataFormat: yaml

# Theme settings
theme: hugo-theme-novela
paginate: 6
social:
  twitter: "#"
  github: "douglasgoodwin"
  instagram: "douglasrgoodwin"
taxonomies:
  author: authors
